[package]
name = "src-jejune"
version = "0.1.0"
edition = "2021"
authors = ["BoyBulbousBemperor", "leinadalrus"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
lindera = "0.18.0"
lindera-core = "0.18.0"